/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Matchbook API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Detect vendors with missing invoices based on billing cycle + last invoice date.
 * @summary Missing Invoice Alerts
 */
export const MissingInvoiceAlertsDashboardMissingInvoicesGetQueryParams = zod.object({
  "as_of": zod.string().optional().describe('Check for missing invoices as of this period (YYYY-MM). Defaults to current month.')
})

export const MissingInvoiceAlertsDashboardMissingInvoicesGetResponse = zod.object({
  "items": zod.array(zod.object({
  "vendor_id": zod.uuid(),
  "vendor_name": zod.string(),
  "billing_cycle": zod.enum(['monthly', 'annual', 'one_off']),
  "last_invoice_period": zod.union([zod.string(),zod.null()]).optional(),
  "expected_period": zod.string()
})),
  "total": zod.number()
})

/**
 * Monthly spend summary — totals, invoice count, match breakdown.
 * @summary Spend Summary
 */
export const SpendSummaryDashboardSpendSummaryGetQueryParams = zod.object({
  "period": zod.string().optional().describe('Period filter (YYYY-MM). Defaults to current month.')
})

export const spendSummaryDashboardSpendSummaryGetResponseTotalSpendExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const spendSummaryDashboardSpendSummaryGetResponseTotalVatRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const spendSummaryDashboardSpendSummaryGetResponseTotalSpendInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const SpendSummaryDashboardSpendSummaryGetResponse = zod.object({
  "total_spend_excl": zod.string().regex(spendSummaryDashboardSpendSummaryGetResponseTotalSpendExclRegExp),
  "total_vat": zod.string().regex(spendSummaryDashboardSpendSummaryGetResponseTotalVatRegExp),
  "total_spend_incl": zod.string().regex(spendSummaryDashboardSpendSummaryGetResponseTotalSpendInclRegExp),
  "invoice_count": zod.number(),
  "matched_count": zod.number(),
  "unmatched_count": zod.number()
})

/**
 * Expenses grouped by category for the given period.
 * @summary Spend By Category
 */
export const SpendByCategoryDashboardSpendByCategoryGetQueryParams = zod.object({
  "period": zod.string().optional().describe('Period filter (YYYY-MM). Defaults to current month.')
})

export const spendByCategoryDashboardSpendByCategoryGetResponseItemsItemTotalExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const spendByCategoryDashboardSpendByCategoryGetResponseItemsItemTotalVatRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const spendByCategoryDashboardSpendByCategoryGetResponseItemsItemTotalInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const SpendByCategoryDashboardSpendByCategoryGetResponse = zod.object({
  "items": zod.array(zod.object({
  "category": zod.string(),
  "total_excl": zod.string().regex(spendByCategoryDashboardSpendByCategoryGetResponseItemsItemTotalExclRegExp),
  "total_vat": zod.string().regex(spendByCategoryDashboardSpendByCategoryGetResponseItemsItemTotalVatRegExp),
  "total_incl": zod.string().regex(spendByCategoryDashboardSpendByCategoryGetResponseItemsItemTotalInclRegExp),
  "invoice_count": zod.number()
}))
})

/**
 * Expenses grouped by vendor for the given period.
 * @summary Spend By Vendor
 */
export const SpendByVendorDashboardSpendByVendorGetQueryParams = zod.object({
  "period": zod.string().optional().describe('Period filter (YYYY-MM). Defaults to current month.')
})

export const spendByVendorDashboardSpendByVendorGetResponseItemsItemTotalExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const spendByVendorDashboardSpendByVendorGetResponseItemsItemTotalVatRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const spendByVendorDashboardSpendByVendorGetResponseItemsItemTotalInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const SpendByVendorDashboardSpendByVendorGetResponse = zod.object({
  "items": zod.array(zod.object({
  "vendor": zod.string(),
  "total_excl": zod.string().regex(spendByVendorDashboardSpendByVendorGetResponseItemsItemTotalExclRegExp),
  "total_vat": zod.string().regex(spendByVendorDashboardSpendByVendorGetResponseItemsItemTotalVatRegExp),
  "total_incl": zod.string().regex(spendByVendorDashboardSpendByVendorGetResponseItemsItemTotalInclRegExp),
  "invoice_count": zod.number()
}))
})

/**
 * VAT breakdown by rate for the given period.
 * @summary Vat Summary
 */
export const VatSummaryDashboardVatSummaryGetQueryParams = zod.object({
  "period": zod.string().optional().describe('Period filter (YYYY-MM). Defaults to current month.')
})

export const vatSummaryDashboardVatSummaryGetResponseItemsItemVatRateRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const vatSummaryDashboardVatSummaryGetResponseItemsItemTotalExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const vatSummaryDashboardVatSummaryGetResponseItemsItemTotalVatRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const VatSummaryDashboardVatSummaryGetResponse = zod.object({
  "items": zod.array(zod.object({
  "vat_rate": zod.string().regex(vatSummaryDashboardVatSummaryGetResponseItemsItemVatRateRegExp),
  "total_excl": zod.string().regex(vatSummaryDashboardVatSummaryGetResponseItemsItemTotalExclRegExp),
  "total_vat": zod.string().regex(vatSummaryDashboardVatSummaryGetResponseItemsItemTotalVatRegExp),
  "invoice_count": zod.number()
}))
})

/**
 * Month-over-month spend comparison for the given year.
 * @summary Mom Comparison
 */
export const MomComparisonDashboardMomComparisonGetQueryParams = zod.object({
  "year": zod.number().optional().describe('Year to compare months for. Defaults to current year.')
})

export const momComparisonDashboardMomComparisonGetResponseItemsItemTotalExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const momComparisonDashboardMomComparisonGetResponseItemsItemTotalVatRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const momComparisonDashboardMomComparisonGetResponseItemsItemTotalInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const MomComparisonDashboardMomComparisonGetResponse = zod.object({
  "items": zod.array(zod.object({
  "period": zod.string(),
  "total_excl": zod.string().regex(momComparisonDashboardMomComparisonGetResponseItemsItemTotalExclRegExp),
  "total_vat": zod.string().regex(momComparisonDashboardMomComparisonGetResponseItemsItemTotalVatRegExp),
  "total_incl": zod.string().regex(momComparisonDashboardMomComparisonGetResponseItemsItemTotalInclRegExp),
  "invoice_count": zod.number()
}))
})

/**
 * Tax and non-invoiceable transactions for the given period (bank fees, tax payments, etc.).
 * @summary Tax Summary
 */
export const TaxSummaryDashboardTaxSummaryGetQueryParams = zod.object({
  "period": zod.string().optional().describe('Period filter (YYYY-MM). Defaults to current month.')
})

export const taxSummaryDashboardTaxSummaryGetResponseTotalAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const taxSummaryDashboardTaxSummaryGetResponseByCategoryItemTotalAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const taxSummaryDashboardTaxSummaryGetResponseItemsItemAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const TaxSummaryDashboardTaxSummaryGetResponse = zod.object({
  "period": zod.string(),
  "total_amount": zod.string().regex(taxSummaryDashboardTaxSummaryGetResponseTotalAmountRegExp),
  "transaction_count": zod.number(),
  "by_category": zod.array(zod.object({
  "category": zod.string(),
  "total_amount": zod.string().regex(taxSummaryDashboardTaxSummaryGetResponseByCategoryItemTotalAmountRegExp),
  "transaction_count": zod.number()
})),
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "tx_date": zod.string(),
  "amount": zod.string().regex(taxSummaryDashboardTaxSummaryGetResponseItemsItemAmountRegExp),
  "description": zod.string(),
  "counterparty": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * Incoming payments (credits) for the given period.
 * @summary Earnings
 */
export const EarningsDashboardEarningsGetQueryParams = zod.object({
  "period": zod.string().optional().describe('Period filter (YYYY-MM). Defaults to current month.')
})

export const earningsDashboardEarningsGetResponseTotalEarningsRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const earningsDashboardEarningsGetResponseItemsItemAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const EarningsDashboardEarningsGetResponse = zod.object({
  "period": zod.string(),
  "total_earnings": zod.string().regex(earningsDashboardEarningsGetResponseTotalEarningsRegExp),
  "transaction_count": zod.number(),
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "tx_date": zod.string(),
  "amount": zod.string().regex(earningsDashboardEarningsGetResponseItemsItemAmountRegExp),
  "description": zod.string(),
  "counterparty": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * Owner withdrawals against earnings for the given period.
 * @summary Withholdings
 */
export const WithholdingsDashboardWithholdingsGetQueryParams = zod.object({
  "period": zod.string().optional().describe('Period filter (YYYY-MM). Defaults to current month.')
})

export const withholdingsDashboardWithholdingsGetResponseTotalAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const withholdingsDashboardWithholdingsGetResponseItemsItemAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const WithholdingsDashboardWithholdingsGetResponse = zod.object({
  "period": zod.string(),
  "total_amount": zod.string().regex(withholdingsDashboardWithholdingsGetResponseTotalAmountRegExp),
  "transaction_count": zod.number(),
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "tx_date": zod.string(),
  "amount": zod.string().regex(withholdingsDashboardWithholdingsGetResponseItemsItemAmountRegExp),
  "description": zod.string(),
  "counterparty": zod.string()
}))
})

