/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Send a message and receive a streaming response.

Uses Server-Sent Events (SSE) to stream the assistant's response.
 * @summary Send Message
 */
export const SendMessageChatMessagePostBody = zod.object({
  "message": zod.string()
})

export const SendMessageChatMessagePostResponse = zod.unknown()

/**
 * @summary Get History
 */
export const GetHistoryChatHistoryGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "role": zod.enum(['user', 'assistant']),
  "content": zod.string(),
  "retrieved_invoice_ids": zod.union([zod.array(zod.uuid()),zod.null()]).optional(),
  "retrieved_tx_ids": zod.union([zod.array(zod.uuid()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})),
  "total": zod.number()
})

/**
 * @summary Clear History
 */
export const ClearHistoryChatHistoryDeleteResponse = zod.object({
  "deleted": zod.number()
})

/**
 * Get contextual chat suggestions based on financial data and conversation history.
 * @summary Get Suggestions
 */
export const GetSuggestionsChatSuggestionsGetResponse = zod.object({
  "questions": zod.array(zod.string())
})

