"""initial_phase1_tables

Revision ID: e7dc78702c5b
Revises: 
Create Date: 2026-03-23 16:43:11.462097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7dc78702c5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('amount_excl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_incl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('drive_url', sa.Text(), nullable=True),
    sa.Column('drive_file_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('gmail', 'portal', 'manual', name='invoice_source'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'matched', 'unmatched', 'flagged', name='invoice_status'), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_type', sa.Enum('gmail_sync', 'portal_scrape', 'reconcile', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('triggered_by', sa.Enum('user', name='triggered_by'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('default_category', sa.Text(), nullable=True),
    sa.Column('default_vat_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('billing_cycle', sa.Enum('monthly', 'bimonthly', 'quarterly', 'annual', 'irregular', name='billing_cycle'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    op.drop_table('job_runs')
    op.drop_table('invoices')
    op.drop_table('categories')
    # ### end Alembic commands ###
