/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Categories
 */
export const ListCategoriesCategoriesGetResponseItem = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "color": zod.string()
})
export const ListCategoriesCategoriesGetResponse = zod.array(ListCategoriesCategoriesGetResponseItem)

