/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Invoices
 */
export const listInvoicesInvoicesGetQuerySkipDefault = 0;
export const listInvoicesInvoicesGetQuerySkipMin = 0;

export const listInvoicesInvoicesGetQueryLimitDefault = 50;
export const listInvoicesInvoicesGetQueryLimitMax = 100;



export const ListInvoicesInvoicesGetQueryParams = zod.object({
  "period": zod.union([zod.string(),zod.null()]).optional().describe('Filter by period e.g. 2026-03'),
  "status": zod.union([zod.string(),zod.null()]).optional().describe('Filter by status'),
  "skip": zod.number().min(listInvoicesInvoicesGetQuerySkipMin).default(listInvoicesInvoicesGetQuerySkipDefault),
  "limit": zod.number().min(1).max(listInvoicesInvoicesGetQueryLimitMax).default(listInvoicesInvoicesGetQueryLimitDefault)
})

export const listInvoicesInvoicesGetResponseItemsItemAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listInvoicesInvoicesGetResponseItemsItemAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listInvoicesInvoicesGetResponseItemsItemVatAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listInvoicesInvoicesGetResponseItemsItemVatRateRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ListInvoicesInvoicesGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "amount_excl": zod.string().regex(listInvoicesInvoicesGetResponseItemsItemAmountExclRegExp),
  "amount_incl": zod.string().regex(listInvoicesInvoicesGetResponseItemsItemAmountInclRegExp),
  "vat_amount": zod.string().regex(listInvoicesInvoicesGetResponseItemsItemVatAmountRegExp),
  "vat_rate": zod.string().regex(listInvoicesInvoicesGetResponseItemsItemVatRateRegExp),
  "invoice_date": zod.iso.date(),
  "invoice_number": zod.string(),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "drive_file_id": zod.union([zod.string(),zod.null()]).optional(),
  "source": zod.enum(['gmail', 'portal', 'manual']),
  "status": zod.enum(['pending', 'matched', 'unmatched', 'flagged']),
  "period": zod.string(),
  "raw_extraction": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})),
  "total": zod.number()
})

/**
 * @summary Create Invoice
 */
export const createInvoiceInvoicesPostBodyAmountExclTwoRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const createInvoiceInvoicesPostBodyAmountInclTwoRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const createInvoiceInvoicesPostBodyVatAmountTwoRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const createInvoiceInvoicesPostBodyVatRateTwoRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const createInvoiceInvoicesPostBodyCurrencyDefault = `EUR`;
export const createInvoiceInvoicesPostBodySourceDefault = `manual`;

export const CreateInvoiceInvoicesPostBody = zod.object({
  "vendor": zod.string(),
  "amount_excl": zod.union([zod.number(),zod.string().regex(createInvoiceInvoicesPostBodyAmountExclTwoRegExp)]),
  "amount_incl": zod.union([zod.number(),zod.string().regex(createInvoiceInvoicesPostBodyAmountInclTwoRegExp)]),
  "vat_amount": zod.union([zod.number(),zod.string().regex(createInvoiceInvoicesPostBodyVatAmountTwoRegExp)]),
  "vat_rate": zod.union([zod.number(),zod.string().regex(createInvoiceInvoicesPostBodyVatRateTwoRegExp)]),
  "invoice_date": zod.iso.date(),
  "invoice_number": zod.string(),
  "currency": zod.string().default(createInvoiceInvoicesPostBodyCurrencyDefault),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "source": zod.enum(['gmail', 'portal', 'manual']).default(createInvoiceInvoicesPostBodySourceDefault),
  "period": zod.string(),
  "raw_extraction": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]).optional()
})

/**
 * @summary Delete All Invoices
 */
export const DeleteAllInvoicesInvoicesDeleteResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Get Invoice
 */
export const GetInvoiceInvoicesInvoiceIdGetParams = zod.object({
  "invoice_id": zod.uuid()
})

export const getInvoiceInvoicesInvoiceIdGetResponseAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getInvoiceInvoicesInvoiceIdGetResponseAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getInvoiceInvoicesInvoiceIdGetResponseVatAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getInvoiceInvoicesInvoiceIdGetResponseVatRateRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const GetInvoiceInvoicesInvoiceIdGetResponse = zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "amount_excl": zod.string().regex(getInvoiceInvoicesInvoiceIdGetResponseAmountExclRegExp),
  "amount_incl": zod.string().regex(getInvoiceInvoicesInvoiceIdGetResponseAmountInclRegExp),
  "vat_amount": zod.string().regex(getInvoiceInvoicesInvoiceIdGetResponseVatAmountRegExp),
  "vat_rate": zod.string().regex(getInvoiceInvoicesInvoiceIdGetResponseVatRateRegExp),
  "invoice_date": zod.iso.date(),
  "invoice_number": zod.string(),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "drive_file_id": zod.union([zod.string(),zod.null()]).optional(),
  "source": zod.enum(['gmail', 'portal', 'manual']),
  "status": zod.enum(['pending', 'matched', 'unmatched', 'flagged']),
  "period": zod.string(),
  "raw_extraction": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Update Invoice
 */
export const UpdateInvoiceInvoicesInvoiceIdPatchParams = zod.object({
  "invoice_id": zod.uuid()
})

export const UpdateInvoiceInvoicesInvoiceIdPatchBody = zod.object({
  "vendor": zod.union([zod.string(),zod.null()]).optional(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['pending', 'matched', 'unmatched', 'flagged']),zod.null()]).optional()
})

export const updateInvoiceInvoicesInvoiceIdPatchResponseAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const updateInvoiceInvoicesInvoiceIdPatchResponseAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const updateInvoiceInvoicesInvoiceIdPatchResponseVatAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const updateInvoiceInvoicesInvoiceIdPatchResponseVatRateRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const UpdateInvoiceInvoicesInvoiceIdPatchResponse = zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "amount_excl": zod.string().regex(updateInvoiceInvoicesInvoiceIdPatchResponseAmountExclRegExp),
  "amount_incl": zod.string().regex(updateInvoiceInvoicesInvoiceIdPatchResponseAmountInclRegExp),
  "vat_amount": zod.string().regex(updateInvoiceInvoicesInvoiceIdPatchResponseVatAmountRegExp),
  "vat_rate": zod.string().regex(updateInvoiceInvoicesInvoiceIdPatchResponseVatRateRegExp),
  "invoice_date": zod.iso.date(),
  "invoice_number": zod.string(),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "drive_file_id": zod.union([zod.string(),zod.null()]).optional(),
  "source": zod.enum(['gmail', 'portal', 'manual']),
  "status": zod.enum(['pending', 'matched', 'unmatched', 'flagged']),
  "period": zod.string(),
  "raw_extraction": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Delete Invoice
 */
export const DeleteInvoiceInvoicesInvoiceIdDeleteParams = zod.object({
  "invoice_id": zod.uuid()
})

/**
 * Manual PDF upload — extracts via LLM, stores invoice.
 * @summary Upload Invoice
 */
export const UploadInvoiceInvoicesUploadPostBody = zod.object({
  "file": zod.instanceof(File)
})

