/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Upload a bank statement file, parse via LLM, store transactions.
 * @summary Upload Statement
 */
export const UploadStatementReconciliationUploadPostBody = zod.object({
  "file": zod.instanceof(File)
})

/**
 * Full reconciliation overview for a period — shows whether the month is complete.
 * @summary Period Overview
 */
export const PeriodOverviewReconciliationOverviewGetQueryParams = zod.object({
  "period": zod.string().describe('Period to reconcile (YYYY-MM)')
})

export const periodOverviewReconciliationOverviewGetResponseTotalInvoicedInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const periodOverviewReconciliationOverviewGetResponseTotalBankDebitsRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const periodOverviewReconciliationOverviewGetResponseNoInvoiceTotalRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const periodOverviewReconciliationOverviewGetResponseWithholdingTotalRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const periodOverviewReconciliationOverviewGetResponseEarningsTotalRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const periodOverviewReconciliationOverviewGetResponseGapRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const periodOverviewReconciliationOverviewGetResponseUnmatchedInvoiceListItemAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const periodOverviewReconciliationOverviewGetResponseUnmatchedTransactionListItemAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const PeriodOverviewReconciliationOverviewGetResponse = zod.object({
  "period": zod.string(),
  "is_complete": zod.boolean(),
  "total_invoices": zod.number(),
  "matched_invoices": zod.number(),
  "unmatched_invoices": zod.number(),
  "total_invoiced_incl": zod.string().regex(periodOverviewReconciliationOverviewGetResponseTotalInvoicedInclRegExp),
  "total_transactions": zod.number(),
  "matched_transactions": zod.number(),
  "unmatched_transactions": zod.number(),
  "total_bank_debits": zod.string().regex(periodOverviewReconciliationOverviewGetResponseTotalBankDebitsRegExp),
  "no_invoice_count": zod.number(),
  "no_invoice_total": zod.string().regex(periodOverviewReconciliationOverviewGetResponseNoInvoiceTotalRegExp),
  "withholding_count": zod.number(),
  "withholding_total": zod.string().regex(periodOverviewReconciliationOverviewGetResponseWithholdingTotalRegExp),
  "earnings_count": zod.number(),
  "earnings_total": zod.string().regex(periodOverviewReconciliationOverviewGetResponseEarningsTotalRegExp),
  "gap": zod.string().regex(periodOverviewReconciliationOverviewGetResponseGapRegExp),
  "unmatched_invoice_list": zod.array(zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "invoice_number": zod.string(),
  "amount_incl": zod.string().regex(periodOverviewReconciliationOverviewGetResponseUnmatchedInvoiceListItemAmountInclRegExp),
  "invoice_date": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional()
})),
  "unmatched_transaction_list": zod.array(zod.object({
  "id": zod.uuid(),
  "counterparty": zod.string(),
  "description": zod.string(),
  "amount": zod.string().regex(periodOverviewReconciliationOverviewGetResponseUnmatchedTransactionListItemAmountRegExp),
  "tx_date": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * Delete all transactions (and their matches), reset linked invoice statuses.
 * @summary Delete All Transactions
 */
export const DeleteAllTransactionsReconciliationTransactionsDeleteResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary List Transactions
 */
export const listTransactionsReconciliationTransactionsGetQuerySkipDefault = 0;
export const listTransactionsReconciliationTransactionsGetQuerySkipMin = 0;

export const listTransactionsReconciliationTransactionsGetQueryLimitDefault = 50;
export const listTransactionsReconciliationTransactionsGetQueryLimitMax = 100;



export const ListTransactionsReconciliationTransactionsGetQueryParams = zod.object({
  "period": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.enum(['unmatched', 'matched', 'no_invoice', 'withholding']),zod.null()]).optional(),
  "skip": zod.number().min(listTransactionsReconciliationTransactionsGetQuerySkipMin).default(listTransactionsReconciliationTransactionsGetQuerySkipDefault),
  "limit": zod.number().min(1).max(listTransactionsReconciliationTransactionsGetQueryLimitMax).default(listTransactionsReconciliationTransactionsGetQueryLimitDefault)
})

export const listTransactionsReconciliationTransactionsGetResponseItemsItemAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listTransactionsReconciliationTransactionsGetResponseItemsItemOriginalAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ListTransactionsReconciliationTransactionsGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "tx_date": zod.iso.date(),
  "value_date": zod.union([zod.iso.date(),zod.null()]).optional(),
  "amount": zod.string().regex(listTransactionsReconciliationTransactionsGetResponseItemsItemAmountRegExp),
  "original_amount": zod.union([zod.string().regex(listTransactionsReconciliationTransactionsGetResponseItemsItemOriginalAmountOneRegExp),zod.null()]).optional(),
  "original_currency": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.string(),
  "counterparty": zod.string(),
  "counterparty_iban": zod.union([zod.string(),zod.null()]).optional(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "note": zod.union([zod.string(),zod.null()]).optional(),
  "period": zod.string(),
  "status": zod.enum(['unmatched', 'matched', 'no_invoice', 'withholding'])
})),
  "total": zod.number()
})

/**
 * Dismiss a transaction — mark as no_invoice with an optional note (e.g. 'currency conversion fee').
 * @summary Dismiss Transaction
 */
export const DismissTransactionReconciliationTransactionsTransactionIdDismissPostParams = zod.object({
  "transaction_id": zod.uuid()
})

export const DismissTransactionReconciliationTransactionsTransactionIdDismissPostBody = zod.object({
  "note": zod.union([zod.string(),zod.null()]).optional()
})

export const dismissTransactionReconciliationTransactionsTransactionIdDismissPostResponseAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const dismissTransactionReconciliationTransactionsTransactionIdDismissPostResponseOriginalAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const DismissTransactionReconciliationTransactionsTransactionIdDismissPostResponse = zod.object({
  "id": zod.uuid(),
  "tx_date": zod.iso.date(),
  "value_date": zod.union([zod.iso.date(),zod.null()]).optional(),
  "amount": zod.string().regex(dismissTransactionReconciliationTransactionsTransactionIdDismissPostResponseAmountRegExp),
  "original_amount": zod.union([zod.string().regex(dismissTransactionReconciliationTransactionsTransactionIdDismissPostResponseOriginalAmountOneRegExp),zod.null()]).optional(),
  "original_currency": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.string(),
  "counterparty": zod.string(),
  "counterparty_iban": zod.union([zod.string(),zod.null()]).optional(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "note": zod.union([zod.string(),zod.null()]).optional(),
  "period": zod.string(),
  "status": zod.enum(['unmatched', 'matched', 'no_invoice', 'withholding'])
})

/**
 * Trigger hybrid matching: deterministic first, then LLM for leftovers.
 * @summary Trigger Matching
 */
export const TriggerMatchingReconciliationMatchPostBody = zod.object({
  "period": zod.union([zod.string(),zod.null()]).optional()
})

export const triggerMatchingReconciliationMatchPostResponseDeterministicMatchesDefault = 0;
export const triggerMatchingReconciliationMatchPostResponseLlmMatchesDefault = 0;
export const triggerMatchingReconciliationMatchPostResponseFeesDismissedDefault = 0;

export const TriggerMatchingReconciliationMatchPostResponse = zod.object({
  "matches_suggested": zod.number(),
  "period": zod.union([zod.string(),zod.null()]).optional(),
  "deterministic_matches": zod.number().default(triggerMatchingReconciliationMatchPostResponseDeterministicMatchesDefault),
  "llm_matches": zod.number().default(triggerMatchingReconciliationMatchPostResponseLlmMatchesDefault),
  "fees_dismissed": zod.number().default(triggerMatchingReconciliationMatchPostResponseFeesDismissedDefault)
})

/**
 * Manually create a match between an unmatched invoice and transaction.
 * @summary Create Match
 */
export const CreateMatchReconciliationMatchesPostBody = zod.object({
  "invoice_id": zod.uuid(),
  "transaction_id": zod.uuid()
}).describe('Manually create a match between an unmatched invoice and transaction.')

/**
 * @summary List Matches
 */
export const listMatchesReconciliationMatchesGetQuerySkipDefault = 0;
export const listMatchesReconciliationMatchesGetQuerySkipMin = 0;

export const listMatchesReconciliationMatchesGetQueryLimitDefault = 50;
export const listMatchesReconciliationMatchesGetQueryLimitMax = 100;



export const ListMatchesReconciliationMatchesGetQueryParams = zod.object({
  "period": zod.union([zod.string(),zod.null()]).optional(),
  "skip": zod.number().min(listMatchesReconciliationMatchesGetQuerySkipMin).default(listMatchesReconciliationMatchesGetQuerySkipDefault),
  "limit": zod.number().min(1).max(listMatchesReconciliationMatchesGetQueryLimitMax).default(listMatchesReconciliationMatchesGetQueryLimitDefault)
})

export const listMatchesReconciliationMatchesGetResponseItemsItemConfidenceRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listMatchesReconciliationMatchesGetResponseItemsItemInvoiceOneAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listMatchesReconciliationMatchesGetResponseItemsItemInvoiceOneAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listMatchesReconciliationMatchesGetResponseItemsItemTransactionOneAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const listMatchesReconciliationMatchesGetResponseItemsItemTransactionOneOriginalAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ListMatchesReconciliationMatchesGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "invoice_id": zod.uuid(),
  "transaction_id": zod.uuid(),
  "confidence": zod.string().regex(listMatchesReconciliationMatchesGetResponseItemsItemConfidenceRegExp),
  "rationale": zod.string(),
  "confirmed_by": zod.enum(['llm', 'user', 'deterministic']),
  "confirmed_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "invoice": zod.union([zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "invoice_number": zod.string(),
  "invoice_date": zod.iso.date(),
  "amount_excl": zod.string().regex(listMatchesReconciliationMatchesGetResponseItemsItemInvoiceOneAmountExclRegExp),
  "amount_incl": zod.string().regex(listMatchesReconciliationMatchesGetResponseItemsItemInvoiceOneAmountInclRegExp),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "period": zod.string()
}),zod.null()]).optional(),
  "transaction": zod.union([zod.object({
  "id": zod.uuid(),
  "tx_date": zod.iso.date(),
  "value_date": zod.union([zod.iso.date(),zod.null()]).optional(),
  "amount": zod.string().regex(listMatchesReconciliationMatchesGetResponseItemsItemTransactionOneAmountRegExp),
  "original_amount": zod.union([zod.string().regex(listMatchesReconciliationMatchesGetResponseItemsItemTransactionOneOriginalAmountOneRegExp),zod.null()]).optional(),
  "original_currency": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.string(),
  "counterparty": zod.string()
}),zod.null()]).optional()
})),
  "total": zod.number()
})

/**
 * @summary Get Match
 */
export const GetMatchReconciliationMatchesMatchIdGetParams = zod.object({
  "match_id": zod.uuid()
})

export const getMatchReconciliationMatchesMatchIdGetResponseConfidenceRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getMatchReconciliationMatchesMatchIdGetResponseInvoiceOneAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getMatchReconciliationMatchesMatchIdGetResponseInvoiceOneAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getMatchReconciliationMatchesMatchIdGetResponseTransactionOneAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getMatchReconciliationMatchesMatchIdGetResponseTransactionOneOriginalAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const GetMatchReconciliationMatchesMatchIdGetResponse = zod.object({
  "id": zod.uuid(),
  "invoice_id": zod.uuid(),
  "transaction_id": zod.uuid(),
  "confidence": zod.string().regex(getMatchReconciliationMatchesMatchIdGetResponseConfidenceRegExp),
  "rationale": zod.string(),
  "confirmed_by": zod.enum(['llm', 'user', 'deterministic']),
  "confirmed_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "invoice": zod.union([zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "invoice_number": zod.string(),
  "invoice_date": zod.iso.date(),
  "amount_excl": zod.string().regex(getMatchReconciliationMatchesMatchIdGetResponseInvoiceOneAmountExclRegExp),
  "amount_incl": zod.string().regex(getMatchReconciliationMatchesMatchIdGetResponseInvoiceOneAmountInclRegExp),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "period": zod.string()
}),zod.null()]).optional(),
  "transaction": zod.union([zod.object({
  "id": zod.uuid(),
  "tx_date": zod.iso.date(),
  "value_date": zod.union([zod.iso.date(),zod.null()]).optional(),
  "amount": zod.string().regex(getMatchReconciliationMatchesMatchIdGetResponseTransactionOneAmountRegExp),
  "original_amount": zod.union([zod.string().regex(getMatchReconciliationMatchesMatchIdGetResponseTransactionOneOriginalAmountOneRegExp),zod.null()]).optional(),
  "original_currency": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.string(),
  "counterparty": zod.string()
}),zod.null()]).optional()
})

/**
 * Reject (delete) a match — resets invoice and transaction to unmatched.
 * @summary Reject Match
 */
export const RejectMatchReconciliationMatchesMatchIdDeleteParams = zod.object({
  "match_id": zod.uuid()
})

export const rejectMatchReconciliationMatchesMatchIdDeleteResponseConfidenceRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const rejectMatchReconciliationMatchesMatchIdDeleteResponseInvoiceOneAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const rejectMatchReconciliationMatchesMatchIdDeleteResponseInvoiceOneAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const rejectMatchReconciliationMatchesMatchIdDeleteResponseTransactionOneAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const rejectMatchReconciliationMatchesMatchIdDeleteResponseTransactionOneOriginalAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const RejectMatchReconciliationMatchesMatchIdDeleteResponse = zod.object({
  "id": zod.uuid(),
  "invoice_id": zod.uuid(),
  "transaction_id": zod.uuid(),
  "confidence": zod.string().regex(rejectMatchReconciliationMatchesMatchIdDeleteResponseConfidenceRegExp),
  "rationale": zod.string(),
  "confirmed_by": zod.enum(['llm', 'user', 'deterministic']),
  "confirmed_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "invoice": zod.union([zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "invoice_number": zod.string(),
  "invoice_date": zod.iso.date(),
  "amount_excl": zod.string().regex(rejectMatchReconciliationMatchesMatchIdDeleteResponseInvoiceOneAmountExclRegExp),
  "amount_incl": zod.string().regex(rejectMatchReconciliationMatchesMatchIdDeleteResponseInvoiceOneAmountInclRegExp),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "period": zod.string()
}),zod.null()]).optional(),
  "transaction": zod.union([zod.object({
  "id": zod.uuid(),
  "tx_date": zod.iso.date(),
  "value_date": zod.union([zod.iso.date(),zod.null()]).optional(),
  "amount": zod.string().regex(rejectMatchReconciliationMatchesMatchIdDeleteResponseTransactionOneAmountRegExp),
  "original_amount": zod.union([zod.string().regex(rejectMatchReconciliationMatchesMatchIdDeleteResponseTransactionOneOriginalAmountOneRegExp),zod.null()]).optional(),
  "original_currency": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.string(),
  "counterparty": zod.string()
}),zod.null()]).optional()
})

/**
 * Confirm a match — updates invoice and transaction status.
 * @summary Confirm Match
 */
export const ConfirmMatchReconciliationMatchesMatchIdConfirmPostParams = zod.object({
  "match_id": zod.uuid()
})

export const ConfirmMatchReconciliationMatchesMatchIdConfirmPostBody = zod.looseObject({

}).describe('Confirm a match — sets confirmed_by to \'user\' and confirmed_at to now.')

export const confirmMatchReconciliationMatchesMatchIdConfirmPostResponseConfidenceRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const confirmMatchReconciliationMatchesMatchIdConfirmPostResponseInvoiceOneAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const confirmMatchReconciliationMatchesMatchIdConfirmPostResponseInvoiceOneAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const confirmMatchReconciliationMatchesMatchIdConfirmPostResponseTransactionOneAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const confirmMatchReconciliationMatchesMatchIdConfirmPostResponseTransactionOneOriginalAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ConfirmMatchReconciliationMatchesMatchIdConfirmPostResponse = zod.object({
  "id": zod.uuid(),
  "invoice_id": zod.uuid(),
  "transaction_id": zod.uuid(),
  "confidence": zod.string().regex(confirmMatchReconciliationMatchesMatchIdConfirmPostResponseConfidenceRegExp),
  "rationale": zod.string(),
  "confirmed_by": zod.enum(['llm', 'user', 'deterministic']),
  "confirmed_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "invoice": zod.union([zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "invoice_number": zod.string(),
  "invoice_date": zod.iso.date(),
  "amount_excl": zod.string().regex(confirmMatchReconciliationMatchesMatchIdConfirmPostResponseInvoiceOneAmountExclRegExp),
  "amount_incl": zod.string().regex(confirmMatchReconciliationMatchesMatchIdConfirmPostResponseInvoiceOneAmountInclRegExp),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "period": zod.string()
}),zod.null()]).optional(),
  "transaction": zod.union([zod.object({
  "id": zod.uuid(),
  "tx_date": zod.iso.date(),
  "value_date": zod.union([zod.iso.date(),zod.null()]).optional(),
  "amount": zod.string().regex(confirmMatchReconciliationMatchesMatchIdConfirmPostResponseTransactionOneAmountRegExp),
  "original_amount": zod.union([zod.string().regex(confirmMatchReconciliationMatchesMatchIdConfirmPostResponseTransactionOneOriginalAmountOneRegExp),zod.null()]).optional(),
  "original_currency": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.string(),
  "counterparty": zod.string()
}),zod.null()]).optional()
})

/**
 * Reassign a match to a different invoice and/or transaction.
 * @summary Reassign Match
 */
export const ReassignMatchReconciliationMatchesMatchIdReassignPatchParams = zod.object({
  "match_id": zod.uuid()
})

export const ReassignMatchReconciliationMatchesMatchIdReassignPatchBody = zod.object({
  "invoice_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "transaction_id": zod.union([zod.uuid(),zod.null()]).optional()
}).describe('Reassign a match to a different invoice or transaction.')

export const reassignMatchReconciliationMatchesMatchIdReassignPatchResponseConfidenceRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const reassignMatchReconciliationMatchesMatchIdReassignPatchResponseInvoiceOneAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const reassignMatchReconciliationMatchesMatchIdReassignPatchResponseInvoiceOneAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const reassignMatchReconciliationMatchesMatchIdReassignPatchResponseTransactionOneAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const reassignMatchReconciliationMatchesMatchIdReassignPatchResponseTransactionOneOriginalAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ReassignMatchReconciliationMatchesMatchIdReassignPatchResponse = zod.object({
  "id": zod.uuid(),
  "invoice_id": zod.uuid(),
  "transaction_id": zod.uuid(),
  "confidence": zod.string().regex(reassignMatchReconciliationMatchesMatchIdReassignPatchResponseConfidenceRegExp),
  "rationale": zod.string(),
  "confirmed_by": zod.enum(['llm', 'user', 'deterministic']),
  "confirmed_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "invoice": zod.union([zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "invoice_number": zod.string(),
  "invoice_date": zod.iso.date(),
  "amount_excl": zod.string().regex(reassignMatchReconciliationMatchesMatchIdReassignPatchResponseInvoiceOneAmountExclRegExp),
  "amount_incl": zod.string().regex(reassignMatchReconciliationMatchesMatchIdReassignPatchResponseInvoiceOneAmountInclRegExp),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "period": zod.string()
}),zod.null()]).optional(),
  "transaction": zod.union([zod.object({
  "id": zod.uuid(),
  "tx_date": zod.iso.date(),
  "value_date": zod.union([zod.iso.date(),zod.null()]).optional(),
  "amount": zod.string().regex(reassignMatchReconciliationMatchesMatchIdReassignPatchResponseTransactionOneAmountRegExp),
  "original_amount": zod.union([zod.string().regex(reassignMatchReconciliationMatchesMatchIdReassignPatchResponseTransactionOneOriginalAmountOneRegExp),zod.null()]).optional(),
  "original_currency": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.string(),
  "counterparty": zod.string()
}),zod.null()]).optional()
})

