/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Generate a financial report in PDF or Excel format and upload to Drive.
 * @summary Generate Report
 */
export const GenerateReportReportsGeneratePostBody = zod.object({
  "timeframe": zod.enum(['single_month', 'quarter', 'ytd', 'full_year', 'custom']),
  "format": zod.enum(['pdf', 'excel']),
  "period": zod.union([zod.string(),zod.null()]).optional(),
  "quarter": zod.union([zod.number(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "from_period": zod.union([zod.string(),zod.null()]).optional(),
  "to_period": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * Preview what a report would contain without generating it.
 * @summary Preview Report
 */
export const PreviewReportReportsPreviewPostBody = zod.object({
  "timeframe": zod.enum(['single_month', 'quarter', 'ytd', 'full_year', 'custom']),
  "format": zod.enum(['pdf', 'excel']),
  "period": zod.union([zod.string(),zod.null()]).optional(),
  "quarter": zod.union([zod.number(),zod.null()]).optional(),
  "year": zod.union([zod.number(),zod.null()]).optional(),
  "from_period": zod.union([zod.string(),zod.null()]).optional(),
  "to_period": zod.union([zod.string(),zod.null()]).optional()
})

export const PreviewReportReportsPreviewPostResponse = zod.object({
  "timeframe_label": zod.string(),
  "periods": zod.array(zod.string()),
  "format": zod.enum(['pdf', 'excel']),
  "filename": zod.string()
})

