/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Jobs
 */
export const listJobsJobsGetQuerySkipDefault = 0;
export const listJobsJobsGetQuerySkipMin = 0;

export const listJobsJobsGetQueryLimitDefault = 20;
export const listJobsJobsGetQueryLimitMax = 100;



export const ListJobsJobsGetQueryParams = zod.object({
  "job_type": zod.union([zod.enum(['gmail_sync', 'portal_scrape', 'reconcile']),zod.null()]).optional(),
  "status": zod.union([zod.enum(['running', 'done', 'failed']),zod.null()]).optional(),
  "skip": zod.number().min(listJobsJobsGetQuerySkipMin).default(listJobsJobsGetQuerySkipDefault),
  "limit": zod.number().min(1).max(listJobsJobsGetQueryLimitMax).default(listJobsJobsGetQueryLimitDefault)
})

export const ListJobsJobsGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "job_type": zod.enum(['gmail_sync', 'portal_scrape', 'reconcile']),
  "status": zod.enum(['running', 'done', 'failed']),
  "triggered_by": zod.enum(['user']),
  "started_at": zod.iso.datetime({}),
  "finished_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "summary": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]).optional()
})),
  "total": zod.number()
})

/**
 * Trigger a new job (gmail_sync, portal_scrape, reconcile).
 * @summary Trigger Job
 */
export const TriggerJobJobsPostBody = zod.object({
  "job_type": zod.enum(['gmail_sync', 'portal_scrape', 'reconcile']),
  "supplier": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Get Job
 */
export const GetJobJobsJobIdGetParams = zod.object({
  "job_id": zod.uuid()
})

export const GetJobJobsJobIdGetResponse = zod.object({
  "id": zod.uuid(),
  "job_type": zod.enum(['gmail_sync', 'portal_scrape', 'reconcile']),
  "status": zod.enum(['running', 'done', 'failed']),
  "triggered_by": zod.enum(['user']),
  "started_at": zod.iso.datetime({}),
  "finished_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "summary": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]).optional()
})

