/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Vendors
 */
export const listVendorsVendorsGetQuerySkipDefault = 0;
export const listVendorsVendorsGetQuerySkipMin = 0;

export const listVendorsVendorsGetQueryLimitDefault = 50;
export const listVendorsVendorsGetQueryLimitMax = 100;



export const ListVendorsVendorsGetQueryParams = zod.object({
  "skip": zod.number().min(listVendorsVendorsGetQuerySkipMin).default(listVendorsVendorsGetQuerySkipDefault),
  "limit": zod.number().min(1).max(listVendorsVendorsGetQueryLimitMax).default(listVendorsVendorsGetQueryLimitDefault)
})

export const listVendorsVendorsGetResponseItemsItemDefaultVatRateOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ListVendorsVendorsGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "aliases": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_category": zod.union([zod.string(),zod.null()]).optional(),
  "default_vat_rate": zod.union([zod.string().regex(listVendorsVendorsGetResponseItemsItemDefaultVatRateOneRegExp),zod.null()]).optional(),
  "billing_cycle": zod.enum(['monthly', 'annual', 'one_off'])
})),
  "total": zod.number()
})

/**
 * @summary Create Vendor
 */
export const createVendorVendorsPostBodyDefaultVatRateTwoRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const createVendorVendorsPostBodyBillingCycleDefault = `monthly`;

export const CreateVendorVendorsPostBody = zod.object({
  "name": zod.string(),
  "aliases": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_category": zod.union([zod.string(),zod.null()]).optional(),
  "default_vat_rate": zod.union([zod.number(),zod.string().regex(createVendorVendorsPostBodyDefaultVatRateTwoRegExp),zod.null()]).optional(),
  "billing_cycle": zod.enum(['monthly', 'annual', 'one_off']).default(createVendorVendorsPostBodyBillingCycleDefault)
})

/**
 * @summary Get Vendor
 */
export const GetVendorVendorsVendorIdGetParams = zod.object({
  "vendor_id": zod.uuid()
})

export const getVendorVendorsVendorIdGetResponseDefaultVatRateOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const GetVendorVendorsVendorIdGetResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "aliases": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_category": zod.union([zod.string(),zod.null()]).optional(),
  "default_vat_rate": zod.union([zod.string().regex(getVendorVendorsVendorIdGetResponseDefaultVatRateOneRegExp),zod.null()]).optional(),
  "billing_cycle": zod.enum(['monthly', 'annual', 'one_off'])
})

/**
 * @summary Update Vendor
 */
export const UpdateVendorVendorsVendorIdPatchParams = zod.object({
  "vendor_id": zod.uuid()
})

export const updateVendorVendorsVendorIdPatchBodyDefaultVatRateTwoRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const UpdateVendorVendorsVendorIdPatchBody = zod.object({
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "aliases": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_category": zod.union([zod.string(),zod.null()]).optional(),
  "default_vat_rate": zod.union([zod.number(),zod.string().regex(updateVendorVendorsVendorIdPatchBodyDefaultVatRateTwoRegExp),zod.null()]).optional(),
  "billing_cycle": zod.union([zod.enum(['monthly', 'annual', 'one_off']),zod.null()]).optional()
})

export const updateVendorVendorsVendorIdPatchResponseDefaultVatRateOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const UpdateVendorVendorsVendorIdPatchResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "aliases": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_category": zod.union([zod.string(),zod.null()]).optional(),
  "default_vat_rate": zod.union([zod.string().regex(updateVendorVendorsVendorIdPatchResponseDefaultVatRateOneRegExp),zod.null()]).optional(),
  "billing_cycle": zod.enum(['monthly', 'annual', 'one_off'])
})

/**
 * @summary Delete Vendor
 */
export const DeleteVendorVendorsVendorIdDeleteParams = zod.object({
  "vendor_id": zod.uuid()
})

export const deleteVendorVendorsVendorIdDeleteResponseDefaultVatRateOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const DeleteVendorVendorsVendorIdDeleteResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "aliases": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "default_category": zod.union([zod.string(),zod.null()]).optional(),
  "default_vat_rate": zod.union([zod.string().regex(deleteVendorVendorsVendorIdDeleteResponseDefaultVatRateOneRegExp),zod.null()]).optional(),
  "billing_cycle": zod.enum(['monthly', 'annual', 'one_off'])
})

/**
 * Get invoice history for a vendor.
 * @summary Get Vendor Invoices
 */
export const GetVendorInvoicesVendorsVendorIdInvoicesGetParams = zod.object({
  "vendor_id": zod.uuid()
})

export const getVendorInvoicesVendorsVendorIdInvoicesGetQuerySkipDefault = 0;
export const getVendorInvoicesVendorsVendorIdInvoicesGetQuerySkipMin = 0;

export const getVendorInvoicesVendorsVendorIdInvoicesGetQueryLimitDefault = 50;
export const getVendorInvoicesVendorsVendorIdInvoicesGetQueryLimitMax = 100;



export const GetVendorInvoicesVendorsVendorIdInvoicesGetQueryParams = zod.object({
  "period": zod.union([zod.string(),zod.null()]).optional(),
  "skip": zod.number().min(getVendorInvoicesVendorsVendorIdInvoicesGetQuerySkipMin).default(getVendorInvoicesVendorsVendorIdInvoicesGetQuerySkipDefault),
  "limit": zod.number().min(1).max(getVendorInvoicesVendorsVendorIdInvoicesGetQueryLimitMax).default(getVendorInvoicesVendorsVendorIdInvoicesGetQueryLimitDefault)
})

export const getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemAmountExclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemAmountInclRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemVatAmountRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');
export const getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemVatRateRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const GetVendorInvoicesVendorsVendorIdInvoicesGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "vendor": zod.string(),
  "amount_excl": zod.string().regex(getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemAmountExclRegExp),
  "amount_incl": zod.string().regex(getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemAmountInclRegExp),
  "vat_amount": zod.string().regex(getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemVatAmountRegExp),
  "vat_rate": zod.string().regex(getVendorInvoicesVendorsVendorIdInvoicesGetResponseItemsItemVatRateRegExp),
  "invoice_date": zod.iso.date(),
  "invoice_number": zod.string(),
  "currency": zod.string(),
  "category": zod.union([zod.string(),zod.null()]).optional(),
  "drive_url": zod.union([zod.string(),zod.null()]).optional(),
  "drive_file_id": zod.union([zod.string(),zod.null()]).optional(),
  "source": zod.enum(['gmail', 'portal', 'manual']),
  "status": zod.enum(['pending', 'matched', 'unmatched', 'flagged']),
  "period": zod.string(),
  "raw_extraction": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})),
  "total": zod.number()
})

