/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export type BillingCycle = typeof BillingCycle[keyof typeof BillingCycle];


export const BillingCycle = {
  monthly: 'monthly',
  annual: 'annual',
  one_off: 'one_off',
} as const;
