/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { ChatRole } from './chatRole';

export interface ChatMessageRead {
  id: string;
  role: ChatRole;
  content: string;
  retrieved_invoice_ids?: string[] | null;
  retrieved_tx_ids?: string[] | null;
  created_at: string;
}
