/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export type ConfirmedBy = typeof ConfirmedBy[keyof typeof ConfirmedBy];


export const ConfirmedBy = {
  llm: 'llm',
  user: 'user',
  deterministic: 'deterministic',
} as const;
