/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export interface EarningsItem {
  tx_date: string;
  amount: string;
  description: string;
  counterparty: string;
  category?: string | null;
}
