/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { InvoiceReadRawExtraction } from './invoiceReadRawExtraction';
import type { InvoiceSource } from './invoiceSource';
import type { InvoiceStatus } from './invoiceStatus';

export interface InvoiceRead {
  id: string;
  vendor: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  amount_excl: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  amount_incl: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  vat_amount: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  vat_rate: string;
  invoice_date: string;
  invoice_number: string;
  currency: string;
  category?: string | null;
  drive_url?: string | null;
  drive_file_id?: string | null;
  source: InvoiceSource;
  status: InvoiceStatus;
  period: string;
  raw_extraction?: InvoiceReadRawExtraction;
  created_at: string;
}
