/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { InvoiceCreateRawExtraction } from './invoiceCreateRawExtraction';
import type { InvoiceSource } from './invoiceSource';

export interface InvoiceCreate {
  vendor: string;
  amount_excl: number | string;
  amount_incl: number | string;
  vat_amount: number | string;
  vat_rate: number | string;
  invoice_date: string;
  invoice_number: string;
  currency?: string;
  category?: string | null;
  source?: InvoiceSource;
  period: string;
  raw_extraction?: InvoiceCreateRawExtraction;
}
