/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { JobReadSummary } from './jobReadSummary';
import type { JobStatus } from './jobStatus';
import type { JobType } from './jobType';
import type { TriggeredBy } from './triggeredBy';

export interface JobRead {
  id: string;
  job_type: JobType;
  status: JobStatus;
  triggered_by: TriggeredBy;
  started_at: string;
  finished_at?: string | null;
  summary?: JobReadSummary;
}
