/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { JobType } from './jobType';

export interface JobTrigger {
  job_type: JobType;
  supplier?: string | null;
}
