/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export type JobType = typeof JobType[keyof typeof JobType];


export const JobType = {
  gmail_sync: 'gmail_sync',
  portal_scrape: 'portal_scrape',
  reconcile: 'reconcile',
} as const;
