/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { JobStatus } from './jobStatus';
import type { JobType } from './jobType';

export type ListJobsJobsGetParams = {
job_type?: JobType | null;
status?: JobStatus | null;
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
