/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionStatus } from './transactionStatus';

export type ListTransactionsReconciliationTransactionsGetParams = {
period?: string | null;
status?: TransactionStatus | null;
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
