/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export type ListInvoicesInvoicesGetParams = {
/**
 * Filter by period e.g. 2026-03
 */
period?: string | null;
/**
 * Filter by status
 */
status?: string | null;
/**
 * Filter by category
 */
category?: string | null;
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
