/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Confirm a match — sets confirmed_by to 'user' and confirmed_at to now.
 */
export interface MatchConfirm { [key: string]: unknown }
