/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { ConfirmedBy } from './confirmedBy';
import type { MatchInvoiceSummary } from './matchInvoiceSummary';
import type { MatchTransactionSummary } from './matchTransactionSummary';

export interface MatchRead {
  id: string;
  invoice_id: string;
  transaction_id: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  confidence: string;
  rationale: string;
  confirmed_by: ConfirmedBy;
  confirmed_at?: string | null;
  invoice?: MatchInvoiceSummary | null;
  transaction?: MatchTransactionSummary | null;
}
