/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export interface MatchTransactionSummary {
  id: string;
  tx_date: string;
  value_date?: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  amount: string;
  original_amount?: string | null;
  original_currency?: string | null;
  description: string;
  counterparty: string;
}
