/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Reassign a match to a different invoice or transaction.
 */
export interface MatchReassign {
  invoice_id?: string | null;
  transaction_id?: string | null;
}
