/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export interface MatchTriggerResponse {
  matches_suggested: number;
  period?: string | null;
  deterministic_matches?: number;
  llm_matches?: number;
  fees_dismissed?: number;
}
