/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export interface MatchInvoiceSummary {
  id: string;
  vendor: string;
  invoice_number: string;
  invoice_date: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  amount_excl: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  amount_incl: string;
  currency: string;
  category?: string | null;
  drive_url?: string | null;
  period: string;
}
