/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { BillingCycle } from './billingCycle';

export interface MissingInvoiceAlert {
  vendor_id: string;
  vendor_name: string;
  billing_cycle: BillingCycle;
  last_invoice_period?: string | null;
  expected_period: string;
}
