/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export type MissingInvoiceAlertsDashboardMissingInvoicesGetParams = {
/**
 * Check for missing invoices as of this period (YYYY-MM). Defaults to current month.
 */
as_of?: string;
};
