/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { UnmatchedInvoiceSummary } from './unmatchedInvoiceSummary';
import type { UnmatchedTransactionSummary } from './unmatchedTransactionSummary';

export interface PeriodReconciliation {
  period: string;
  is_complete: boolean;
  total_invoices: number;
  matched_invoices: number;
  unmatched_invoices: number;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  total_invoiced_incl: string;
  total_transactions: number;
  matched_transactions: number;
  unmatched_transactions: number;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  total_bank_debits: string;
  no_invoice_count: number;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  no_invoice_total: string;
  withholding_count: number;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  withholding_total: string;
  earnings_count: number;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  earnings_total: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  gap: string;
  unmatched_invoice_list: UnmatchedInvoiceSummary[];
  unmatched_transaction_list: UnmatchedTransactionSummary[];
}
