/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { ReportFormat } from './reportFormat';
import type { TimeframeType } from './timeframeType';

export interface ReportRequest {
  timeframe: TimeframeType;
  format: ReportFormat;
  period?: string | null;
  quarter?: number | null;
  year?: number | null;
  from_period?: string | null;
  to_period?: string | null;
}
