/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */

export type TimeframeType = typeof TimeframeType[keyof typeof TimeframeType];


export const TimeframeType = {
  single_month: 'single_month',
  quarter: 'quarter',
  ytd: 'ytd',
  full_year: 'full_year',
  custom: 'custom',
} as const;
