/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { BillingCycle } from './billingCycle';

export interface VendorUpdate {
  name?: string | null;
  aliases?: string[] | null;
  default_category?: string | null;
  default_vat_rate?: number | string | null;
  billing_cycle?: BillingCycle | null;
}
