/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenReconFi API
 * Self-hosted agency finance ops — invoice collection, reconciliation, reporting.
 * OpenAPI spec version: 0.1.0
 */
import type { WithholdingTransaction } from './withholdingTransaction';

export interface WithholdingSummary {
  period: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  total_amount: string;
  transaction_count: number;
  items: WithholdingTransaction[];
}
